import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
// PrismaClient is generated by `prisma generate`; run it so types exist (see backend README/setup).
// @ts-ignore - module resolution may fail until prisma generate has been run
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {
  constructor() {
    super({
      log:
        process.env.NODE_ENV === 'development'
          ? ['query', 'error', 'warn']
          : ['error'],
    });
  }

  async onModuleInit() {
    await (this as unknown as { $connect(): Promise<void> }).$connect();
  }

  async onModuleDestroy() {
    await (this as unknown as { $disconnect(): Promise<void> }).$disconnect();
  }
}
